build:
  nodes:
      analysis:
          tests:
              override:
                  - php-scrutinizer-run
      tests-and-coverage:
          environment:
              php: 7.1
              postgresql: false
              redis: false
          tests:
              override:
                  -
                      command: 'vendor/bin/phpunit --coverage-clover=cloverCoverage'
                      coverage:
                          file: 'cloverCoverage'
                          format: 'clover'

filter:
  dependency_paths:
    - "propel/"
  excluded_paths:
    - "app/"
    - "config/"
    - "bin/"
    - "storage/"
    - "tests/"
    - "vendor/"
